import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-[#0d0d12] px-6 py-16 text-white">
      <Link
        href="/dashboard/settings"
        className="fixed left-6 top-6 z-50 flex items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-500/10 px-3 py-2 text-sm text-violet-300 backdrop-blur-md transition hover:border-violet-400/30 hover:bg-violet-500/20 hover:text-violet-200"
      >
        <ArrowLeft size={16} />
        Back
      </Link>
      <div className="mx-auto max-w-4xl">
        <div className="mb-12">
          <p className="mb-3 text-sm font-medium text-violet-400">Queuerious</p>

          <h1 className="text-4xl font-semibold tracking-tight">
            Privacy Policy
          </h1>

          <p className="mt-4 text-sm text-white/40">
            Last updated: September 5, 2026
          </p>
        </div>

        <div className="space-y-10 text-sm leading-7 text-white/65">
          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              1. Introduction
            </h2>

            <p>
              Queuerious is a social discovery and connection service that helps
              users meet and interact with other people through profiles,
              preferences, matching, conversations, and the Queuemitment
              experience.
            </p>

            <p className="mt-4">
              This Privacy Policy explains what information we collect, how we
              use it, how we store it, and the circumstances in which it may be
              processed by service providers that help us operate Queuerious.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              2. Information We Collect
            </h2>

            <p>
              Depending on how you use Queuerious, we may collect and process
              the following categories of information:
            </p>

            <h3 className="mb-2 mt-6 font-medium text-white">
              Account information
            </h3>

            <ul className="list-disc space-y-2 pl-5">
              <li>Email address</li>
              <li>Account identifier</li>
              <li>Authentication and account-related information</li>
            </ul>

            <h3 className="mb-2 mt-6 font-medium text-white">
              Profile information
            </h3>

            <ul className="list-disc space-y-2 pl-5">
              <li>First name</li>
              <li>Date of birth</li>
              <li>Gender</li>
              <li>Height</li>
              <li>Location</li>
              <li>Country</li>
              <li>Biography</li>
              <li>Interests</li>
              <li>Profile photographs</li>
            </ul>

            <h3 className="mb-2 mt-6 font-medium text-white">
              Matching and preference information
            </h3>

            <ul className="list-disc space-y-2 pl-5">
              <li>Gender preferences</li>
              <li>Preferred age range</li>
              <li>Location preferences</li>
              <li>Connection and relationship preferences</li>
            </ul>

            <h3 className="mb-2 mt-6 font-medium text-white">
              Queuemitment and matching information
            </h3>

            <ul className="list-disc space-y-2 pl-5">
              <li>Queue participation</li>
              <li>Match information</li>
              <li>Connection type</li>
              <li>Connection status</li>
              <li>Decisions and readiness states</li>
              <li>Extension requests and related activity</li>
              <li>Last-seen information</li>
              <li>Relevant timestamps</li>
            </ul>

            <h3 className="mb-2 mt-6 font-medium text-white">
              Messages and user-generated content
            </h3>

            <p>
              When users communicate through Queuerious, we process and store
              the messages they send, including message content, sender
              information, conversation identifiers, message type, and
              timestamps.
            </p>

            <h3 className="mb-2 mt-6 font-medium text-white">
              Notifications and settings
            </h3>

            <p>
              We may store notifications generated by the service, including
              their type, title, message, creation time, and read status. We
              also store whether a user has enabled or disabled notifications.
            </p>

            <h3 className="mb-2 mt-6 font-medium text-white">
              Tokens and service usage
            </h3>

            <p>
              We process information relating to Queue Tokens, including token
              balances and timestamps associated with free-token and
              advertising-related rewards.
            </p>

            <h3 className="mb-2 mt-6 font-medium text-white">
              Referral information
            </h3>

            <p>
              If you participate in our referral program, we may process
              referral codes, referral relationships, reward information, and a
              hashed representation of an email address for the purpose of
              preventing abuse and duplicate rewards.
            </p>

            <h3 className="mb-2 mt-6 font-medium text-white">
              Subscription information
            </h3>

            <p>
              If you purchase a Queuerious membership, we process information
              about your subscription, including the selected plan, status,
              activation and expiration dates, cancellation information, and the
              relevant payment-provider subscription identifier.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              3. How We Use Information
            </h2>

            <p>We use information to:</p>

            <ul className="mt-4 list-disc space-y-2 pl-5">
              <li>Provide and operate the Queuerious service</li>
              <li>Create and manage user accounts</li>
              <li>Display user profiles and preferences</li>
              <li>Provide matching and Queuemitment functionality</li>
              <li>Enable conversations between matched users</li>
              <li>Deliver service notifications</li>
              <li>Manage Queue Tokens and rewards</li>
              <li>Operate the referral program</li>
              <li>Process subscriptions and purchases</li>
              <li>Prevent abuse, fraud, and unauthorized activity</li>
              <li>Maintain and secure the service</li>
              <li>Comply with applicable legal obligations</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              4. Profile Photos
            </h2>

            <p>
              Users may upload photographs to their Queuerious profiles. Profile
              photographs are stored using our cloud storage infrastructure and
              may be displayed to other users as part of the Queuerious service.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              5. Service Providers
            </h2>

            <p>
              We use trusted third-party service providers to operate different
              parts of Queuerious. These providers may process information on
              our behalf or process information in accordance with their own
              applicable privacy terms.
            </p>

            <h3 className="mb-2 mt-6 font-medium text-white">Supabase</h3>

            <p>
              We use Supabase for authentication, database infrastructure, cloud
              storage, and real-time functionality. Our Supabase project is
              hosted in the European Union.
            </p>

            <h3 className="mb-2 mt-6 font-medium text-white">Stripe</h3>

            <p>
              We use Stripe to process purchases and subscriptions. Payment card
              details are processed by Stripe and are not stored directly in the
              Queuerious database.
            </p>

            <h3 className="mb-2 mt-6 font-medium text-white">Google</h3>

            <p>
              We may use Google advertising and consent-management services to
              display advertisements and manage applicable privacy choices.
              These services may use cookies, web beacons, IP addresses, and
              other identifiers as described by Google.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              6. Advertising and Cookies
            </h2>

            <p>
              Queuerious may use advertising technologies provided by Google.
              Advertising services may use cookies or similar technologies to
              serve and measure advertisements.
            </p>

            <p className="mt-4">
              Third-party advertising providers may place or read cookies on a
              user&apos;s browser and may process information such as IP
              addresses or other identifiers in connection with advertising.
            </p>

            <p className="mt-4">
              Where required by applicable law, advertising-related consent
              choices are presented and managed through our consent management
              solution.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              7. Rewarded Advertising
            </h2>

            <p>
              Queuerious may offer optional rewarded advertisements. Users may
              voluntarily choose to view an advertisement in exchange for an
              in-service reward, such as Queue Tokens or access to certain
              functionality.
            </p>

            <p className="mt-4">
              A reward is provided only when the applicable rewarded advertising
              experience has been successfully completed.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              8. Cookies and Authentication
            </h2>

            <p>
              Queuerious uses cookies and similar browser storage mechanisms
              necessary for authentication, session management, and the secure
              operation of the service.
            </p>

            <p className="mt-4">
              We do not currently operate a separate analytics platform such as
              Google Analytics, Sentry, Vercel Analytics, or Vercel Speed
              Insights.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              9. Data Storage and Security
            </h2>

            <p>
              We take reasonable technical and organizational measures to
              protect information against unauthorized access, alteration,
              disclosure, or destruction.
            </p>

            <p className="mt-4">
              Information stored through our Supabase infrastructure is hosted
              in the European Union. However, some third-party service providers
              may process information in other countries where their
              infrastructure or legal requirements require it.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              10. Data Retention
            </h2>

            <p>
              We retain information for as long as reasonably necessary to
              provide the service, maintain account functionality, comply with
              legal obligations, resolve disputes, enforce agreements, and
              prevent abuse.
            </p>

            <p className="mt-4">
              When an account is deleted, we delete the account and associated
              Queuerious data in accordance with our account-deletion processes,
              subject to information that may need to be retained where required
              by law or for legitimate security purposes.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              11. Your Rights
            </h2>

            <p>
              Depending on your location and applicable law, you may have rights
              relating to your personal information, including the right to
              access, correct, delete, restrict, or object to certain processing
              of your information.
            </p>

            <p className="mt-4">
              You may also have the right to withdraw consent where processing
              is based on consent.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              12. Account Deletion
            </h2>

            <p>
              Queuerious provides an account-deletion function through the
              application. Account deletion removes the account and the
              associated Queuerious data according to our deletion process,
              subject to applicable legal or security retention requirements.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              13. Children
            </h2>

            <p>
              Queuerious is intended for users who are 18 years of age or older.
              We do not knowingly allow anyone under the age of 18 to create or
              use an account. If we learn that a person under 18 has created an
              account, we will take reasonable steps to remove the account and
              associated personal information.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              14. Changes to This Policy
            </h2>

            <p>
              We may update this Privacy Policy from time to time to reflect
              changes to the service, our practices, or applicable legal
              requirements. When we make changes, we will update the &quot;Last
              updated&quot; date shown at the top of this page.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-white">
              15. Contact
            </h2>

            <p>
              If you have questions or requests relating to this Privacy Policy
              or your personal information, please contact the Queuerious team
              through the contact method made available through the service.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
